### ISSUE TITLE
咨询项目后续开发计划

### ISSUE THREAD

**Issue by Domn93** [molsionmo/flink-sql-client#1]
感谢作者的开源精神，想请问这个项目后续会支持YarnPer提交模式，以及会跟随Flink升级到1.10.x吗？

**Comment by lijufeng2016** [comment]
同问+1

**Comment by molsionmo** [comment]
感谢各位的关注，升级至1.10和1.11是在计划中了, 预计会先支持1.10(时间将在8~9月份左右)

在1.10版本逐步稳定后将进入1.11的版本迭代支持中

**Comment by Domn93** [comment]
YarnPer提交模式也会后续支持吗？ 目前看好像只能提交 yarn session模式

**Comment by molsionmo** [comment]
YarnPer后续是会支持的, 这个特性将会优先支持1.9.1，开发计划也在安排了

**Comment by Domn93** [comment]
感谢回复

**Comment by YuYuYan** [comment]
后续开发的链接呢
